apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ingress
  name: traefik-ingress-controller

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  namespace: ingress
  name: traefik
  labels:
    app: traefik

spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      hostNetwork: true
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      nodeSelector:
        cloud.google.com/gke-nodepool: stable-pool
      containers:
        - name: traefik
          image: traefik:v2.2
          args:
            #- --log.level=DEBUG
            - --api.insecure
            - --accesslog
            - --ping
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetescrd
            - --certificatesresolvers.myresolver.acme.tlschallenge
            - --certificatesresolvers.myresolver.acme.email=shuuji3@gmail.com
            - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            #- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          volumeMounts:
            - mountPath: /letsencrypt
              name: traefik-letsencrypt
              readOnly: false
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: admin
              containerPort: 8080
      volumes:
        - name: traefik-letsencrypt
          configMap:
            name: traefik-letsencrypt
            defaultMode: 0600
