apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-pv-claim-letsencrypt
  namespace: ingress
  labels:
    app: traefik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
